# initital agent for each rank

# Agent Type
FIRM_TYPE: &FIRM_TYPE 0
CEN_PLANNER_TYPE: &CEN_PLANNER_TYPE 1
CEN_PLANNER_REPORTER_TYPE: &CEN_PLANNER_REPORTER_TYPE 2
COMM_BANK_TYPE: &COMM_BANK_TYPE 3
COMM_BANK_REPORTER_TYPE: &COMM_BANK_REPORTER_TYPE 4
CEN_BANK_TYPE: &CEN_BANK_TYPE 5
CEN_BANK_REPORTER_TYPE: &CEN_BANK_REPORTER_TYPE 6

# -------------- Agent Parameters ------------------
agent_params:
  *COMM_BANK_TYPE:
    &basic_bank 0:
      depositInterestRate: 0.001
      loanInterestRate: 0.0012

#  ------------- create agents ----------------------
agent_distribute_mode: mean



agents:
  *COMM_BANK_TYPE:
    total_amount: 6
    groups:
      local_banks:
        share: 0
        sectorialClass:
          # parameter group
          *basic_bank
        isGlobal: false

      global_banks:
        share: 0.2
        sectorialClass:
          # parameter group
          *basic_bank
        isGlobal: true

