# initital agent for each rank

# Agent Type
FIRM_TYPE: &FIRM_TYPE 0
CEN_PLANNER_TYPE: &CEN_PLANNER_TYPE 1
CEN_PLANNER_REPORTER_TYPE: &CEN_PLANNER_REPORTER_TYPE 2
COMM_BANK_TYPE: &COMM_BANK_TYPE 3
CEN_BANK_TYPE: &CEN_BANK_TYPE 4
HOUSEHOLD_TYPE: &HOUSEHOLD_TYPE 5

CREDIT_MARKET_TYPE: &CREDIT_MARKET_TYPE 100
CONSUMPTION_MARKET_TYPE: &CONSUMPTION_MARKET_TYPE 101

# -------------- Agent Parameters ------------------n
agent_params:
  *COMM_BANK_TYPE:
    param_name: [depositInterestRate, loanInterestRate]
    &default_bank 0:
#      depositInterestRate: 0.001
#      loanInterestRate: 0.0012
#      targetedLiquidityRatio: 0.17
#      capitalAdequacyRatio: 0.06

      depositInterestRate: 0.001
      loanInterestRate: 0.0012
      targetedLiquidityRatio: 0.17
      capitalAdequacyRatio: 0.06


  *CEN_BANK_TYPE:
    param_name: [advanceInterestRate]
    &default_cen_bank 0:
#      advanceInterestRate: 0.0001
      advanceInterestRate: 0.0001

  *CEN_PLANNER_TYPE:
    param_name: []
    &default_cen_planner 0:
      #incrementAndSubstitutions = 'zero', 'random', 'total', 'proportionally' # to be accorded with the name of the folder in the experiments
      incrementAndSubstitutions: 'total'
      #askingMaxInvGoodsProduction = 'min', 'regular', 'max' # to be accorded with the name of the folder in the experiments -> PropMin, PropMax
      # relevant only under the case of incrementAndSubstitutions = 'proportionally'
      askingInvGoodsProduction: 'max' # OR 'regular' (basic option) OR 'min' OR 'max'
      investmentVariation: 0.8 # positive or negative in (-1,+1)
      #used as 1+investmentVariation for the cases 'min' (must be negative) or 'max' (must be positive)
      #################################################
      #order generation (alternatively)
      noOrderGeneration: false
      randomOrderGeneration: true
      #################################################
      #modify duration
      durationCoeff: 2

  *HOUSEHOLD_TYPE :
    param_name: []
    &default_household 0:



  *CREDIT_MARKET_TYPE:
    param_name: []
    &default_credit_market 0:
      nround: 1

  *CONSUMPTION_MARKET_TYPE :
    param_name: [ ]
    &default_consumption_market 0:
      nround: 10




#  ------------- create agents ----------------------
agent_distribute_mode: mean



agents:
  *COMM_BANK_TYPE:
    total_amount: 100
    groups:
      local_banks:
        share: 0.2
        paramGroup:
          # parameter group
          *default_bank
        isGlobal: false

      global_banks:
        share: 0.8
        paramGroup:
          # parameter group
          *default_bank
        isGlobal: true

  *CEN_BANK_TYPE:
    total_amount: 1
    groups:
      unique:
        share: 1
        paramGroup:
          *default_cen_bank
        isGlobal: true

  *HOUSEHOLD_TYPE :
    total_amount: 1000
    groups:
      local_household:
        share: 1
        paramGroup:
          *default_household
        isGlobal: False

  *CEN_PLANNER_TYPE:
    total_amount: 1
    groups:
      unique:
        share: 1
        paramGroup:
          *default_cen_planner
        isGlobal: true

  *CREDIT_MARKET_TYPE :
    total_amount: 1
    groups:
      unique:
        share: 1
        paramGroup:
          *default_credit_market
        isGlobal: true

  *CONSUMPTION_MARKET_TYPE :
    total_amount: 1
    groups:
      unique:
        share: 1
        paramGroup:
          *default_consumption_market
        isGlobal: true
